/**
 * What the help search can find. One entry per thing a podcaster or a
 * listener asks about, with the page that answers it and the words they
 * tend to use. Kept by hand: it is the map of the help, not the help itself.
 */
export interface HelpEntry {
  title: string;
  summary: string;
  href: string;
  keywords: string;
  /** Where it applies: everyone, or people on the lineup. */
  audience: "everyone" | "podcasters";
  /** The shelf it sits on, on the help hub. */
  category: HelpCategory;
  /** A question from the FAQ: found by search, and reached from the shelf's "More questions" link. */
  faq?: boolean;
}

export type HelpCategory = "lineup" | "showday" | "create" | "postify" | "youtube" | "grow" | "account" | "watching" | "sponsors";
export const HELP_CATEGORIES: { key: HelpCategory; title: string; blurb: string }[] = [
  { key: "lineup", title: "Getting on the lineup", blurb: "Your sign-in, your slot, your photo and your card." },
  { key: "showday", title: "Show day", blurb: "The green room, going live, a recorded episode, co-hosting." },
  { key: "create", title: "Rooms and your Library", blurb: "Record with guests, go live, and keep every episode and clip in one place." },
  { key: "postify", title: "Pōstify: edit and post", blurb: "Trim and cut your episode, add music, fix up clips, and post them." },
  { key: "youtube", title: "Your podcast, YouTube and Zoom", blurb: "Your show in Apple and Spotify, your segment on your channel, your Zoom recordings in your Library." },
  { key: "grow", title: "SmartLink and guests", blurb: "Your page and talking intro, guests to book, and shows to pitch." },
  { key: "account", title: "Your account", blurb: "Your plan, credits and billing, and putting back what you deleted." },
  { key: "watching", title: "Watching the marathon", blurb: "What it is, when it is, and how to catch a show." },
  { key: "sponsors", title: "Sponsors", blurb: "Backing a show, and what a sponsor gets." },
];

export const HELP_INDEX: HelpEntry[] = [
  {
    title: "Get your podcast into Apple Podcasts and Spotify",
    summary: "Your feed, what the apps need first, and submitting it once to each. New episodes then go out on their own.",
    href: "/help/podcast",
    keywords: "podcast hosting rss feed apple podcasts spotify list submit connect creators directory cover art description owner email category publish",
    audience: "podcasters",
    category: "youtube",
  },
  {
    title: "Take your podcast down from Apple and Spotify",
    summary: "Remove it in Podcasts Connect and Spotify for Creators first, then delete the show here.",
    href: "/help/podcast#unlist",
    keywords: "podcast unlist remove delete take down apple spotify hide show feed",
    audience: "podcasters",
    category: "youtube",
  },
  {
    title: "Move your podcast here, or away, with a 301",
    summary: "Import your feed, turn on the redirect at your old host, then Check the redirect. Moving away: Moving to another host? in Show details.",
    href: "/help/podcast#move",
    keywords: "podcast move host migrate import redirect 301 new feed url forward subscribers buzzsprout libsyn anchor spotify for creators podbean transistor",
    audience: "podcasters",
    category: "youtube",
  },
  {
    title: "Send your slot to your own YouTube",
    summary: "Connect your channel once and your segment streams there too, live. A 45-second video and the steps.",
    href: "/help/youtube",
    keywords: "youtube connect channel stream live integrations google verified advanced continue scope broadcast",
    audience: "podcasters",
    category: "youtube",
  },
  {
    title: "Google says the app isn't verified",
    summary: "That screen is expected while we're in Google's review. Press Advanced, then Go to Military Voice (unsafe), then Continue.",
    href: "/help/youtube#verified",
    keywords: "google not verified unverified warning advanced continue access blocked review",
    audience: "podcasters",
    category: "youtube",
  },
  {
    title: "Bring your Zoom recordings into your Library",
    summary: "Connect Zoom once in Integrations and your cloud recordings come into your Library, ready for Pōstify.",
    href: "/help/zoom",
    keywords: "zoom connect cloud recording recordings import library integrations meeting marketplace app postify pōstify",
    audience: "podcasters",
    category: "youtube",
  },
  {
    title: "Import past Zoom recordings",
    summary: "Press Import past recordings on the Zoom card, pick from the last 30 days, and it shows in your Library.",
    href: "/help/zoom#use",
    keywords: "zoom past old recordings import 30 days mp4 importing from zoom automatic auto new recording switch",
    audience: "podcasters",
    category: "youtube",
  },
  {
    title: "Disconnect or remove the Zoom app",
    summary: "Press Disconnect on the Zoom card, or remove MilitaryVoices in Zoom's App Marketplace. The connection is deleted at once.",
    href: "/help/zoom#remove",
    keywords: "zoom disconnect remove uninstall deauthorize revoke delete data marketplace added apps privacy scopes",
    audience: "podcasters",
    category: "youtube",
  },
  {
    title: "Record and go live in your room",
    summary: "Rooms is quick, like Zoom. Press Enter my room, check your camera and mic, and you're in. Record, go live, bring guests.",
    href: "/help/rooms",
    keywords: "rooms room my room enter my room zoom-like quick record go live studio camera mic microphone meeting video call my studio",
    audience: "podcasters",
    category: "create",
  },
  {
    title: "Invite a guest to your room",
    summary: "Copy link on the Rooms screen, or Invite a guest in the room. No account needed. New link stops the old one.",
    href: "/help/rooms#invite",
    keywords: "invite guest link join room no account copy link new link expired guest can't get in",
    audience: "podcasters",
    category: "create",
  },
  {
    title: "Record in your room",
    summary: "Press Record, then Stop recording. It's in your Library in a minute or two, ready for Pōstify.",
    href: "/help/rooms#record",
    keywords: "record recording rec stop recording room library saved where is my recording",
    audience: "podcasters",
    category: "create",
  },
  {
    title: "Go live to YouTube or Facebook from your room",
    summary: "Go live streams to YouTube and any streaming keys you've switched on. YouTube needs live streaming turned on first; it can take a day.",
    href: "/help/rooms#live",
    keywords: "go live stream streaming youtube live facebook twitch linkedin kick rtmp stream key server live streaming not enabled end live",
    audience: "podcasters",
    category: "create",
  },
  {
    title: "Add a streaming key",
    summary: "Add a streaming key on the Rooms screen: a name, the server (rtmp://) and the key. Switch each on or off.",
    href: "/help/rooms#keys",
    keywords: "streaming key stream key rtmp rtmps server facebook twitch kick linkedin add a streaming key multistream",
    audience: "podcasters",
    category: "create",
  },
  {
    title: "Rooms or Studio?",
    summary: "Rooms is here now. Studio, the full marathon studio for your own show, is coming October 5.",
    href: "/help/rooms#studio",
    keywords: "studio coming soon october 5 oct 5th marathon studio scenes layouts lower thirds producer console rooms difference",
    audience: "podcasters",
    category: "create",
  },
  {
    title: "Your Library: episodes and clips",
    summary: "Episodes and Clips tabs, and counts that take you places: Clips made, Episodes, and Posts sent on the Social calendar.",
    href: "/help/library",
    keywords: "library episodes clips tabs counts clips made posts sent time saved hours recorded upload folders 4 clips",
    audience: "podcasters",
    category: "create",
  },
  {
    title: "Clean, Edited and Original versions",
    summary: "Switch between the versions on an episode's card. Older edits wait under Earlier edits.",
    href: "/help/library#versions",
    keywords: "clean edited original version versions earlier edits which copy download edit copy",
    audience: "podcasters",
    category: "create",
  },
  {
    title: "Scheduled or Posted clips",
    summary: "On the Clips tab, navy Scheduled is waiting in your queue; green Posted is out.",
    href: "/help/library#clips",
    keywords: "scheduled posted badge queue clip status posted clips filter episode",
    audience: "podcasters",
    category: "create",
  },
  {
    title: "Edit an episode in Pōstify",
    summary: "Open an episode, choose Edit episode, trim the ends, take out sections, add music. Your original stays as it is.",
    href: "/help/postify",
    keywords: "postify pōstify edit episode editor timeline cut clean episode make clips",
    audience: "podcasters",
    category: "postify",
  },
  {
    title: "Trim the start and end of an episode",
    summary: "Press Trim start & end (the bracket icon), drag the yellow handles, then Done.",
    href: "/help/postify#trim",
    keywords: "trim start end beginning handles yellow bracket cut the start cut the end",
    audience: "podcasters",
    category: "postify",
  },
  {
    title: "Take out a section with Split",
    summary: "Split (the scissors) at the start and end of it, click the piece, then Delete, or Take out … · Done.",
    href: "/help/postify#split",
    keywords: "split scissors cut out remove section middle delete piece take out done suggest edits",
    audience: "podcasters",
    category: "postify",
  },
  {
    title: "Your edits, drafts and Save to Library",
    summary: "Your edits lists each change with undo. Drafts save as you go. Save to Library makes a new copy; nothing goes to your podcast until you add it.",
    href: "/help/postify#edits",
    keywords: "your edits undo undo all draft saved save & close save and close save to library new copy original add to my podcast",
    audience: "podcasters",
    category: "postify",
  },
  {
    title: "Add music to an episode",
    summary: "Music: the opening, the close, a piece you picked, or the whole episode, under the voices or full.",
    href: "/help/postify#music",
    keywords: "music track song background under the voices full opening close whole episode",
    audience: "podcasters",
    category: "postify",
  },
  {
    title: "Add an intro or outro",
    summary: "Press Intro or Outro at either end of the timeline, and pick Fade, Dip to black or Cut.",
    href: "/help/postify#intro",
    keywords: "intro outro bumper opener closer transition fade dip to black cut",
    audience: "podcasters",
    category: "postify",
  },
  {
    title: "Trim a clip or change its title",
    summary: "In a clip's menu: Trim this clip, or Edit the title and text with Suggest titles. Its music stays.",
    href: "/help/postify#clips",
    keywords: "clip trim this clip edit the title and text suggest titles subtitle headline rename clip music remake shapes",
    audience: "podcasters",
    category: "postify",
  },
  {
    title: "Post an episode or its clips",
    summary: "A whole episode goes to YouTube only. Post its clips to Instagram, TikTok, Facebook and LinkedIn.",
    href: "/help/postify#post",
    keywords: "post posting share instagram tiktok facebook linkedin youtube 15 minutes too long schedule next open slot social calendar",
    audience: "podcasters",
    category: "postify",
  },
  {
    title: "Your podcast episodes on YouTube",
    summary: "Per show: Ask me each time, or Always post it to YouTube, Public or Unlisted. Never the same video twice.",
    href: "/help/podcast#youtube",
    keywords: "podcast youtube publish episode video ask me each time always post it to youtube public unlisted also post it to youtube not this one undo post now twice duplicate",
    audience: "podcasters",
    category: "youtube",
  },
  {
    title: "Delete one podcast episode",
    summary: "It leaves your feed and the apps drop it on their next check. It stays on YouTube. Put it back within 15 days.",
    href: "/help/podcast#unlist",
    keywords: "delete episode remove episode feed apps youtube put it back undo",
    audience: "podcasters",
    category: "youtube",
  },
  {
    title: "Adjust the Hero top of your SmartLink",
    summary: "Hero, in Design: Name size, Name position, Photo position and Photo size sliders, and Reset.",
    href: "/help/smartlink#hero",
    keywords: "smartlink hero top of the page name size name position photo position photo size slider zoom crop head cut off design layout",
    audience: "podcasters",
    category: "grow",
  },
  {
    title: "Email your fans",
    summary: "Write to everyone who signed up on your SmartLink: blocks, a live preview, a test to yourself, then send or schedule.",
    href: "/help/smartlink#fans",
    keywords: "email your fans newsletter subscribers stay in touch list mailing list campaign send email to my audience unsubscribe schedule",
    audience: "podcasters",
    category: "grow",
  },
  {
    title: "Make a talking intro",
    summary: "Your photo says hello on your SmartLink, in your own voice or one you pick, like the Marine voices Brock, Sarge and Jerry.",
    href: "/help/smartlink#intro",
    keywords: "talking intro video bubble hello voice record my hello brock sarge jerry marine voices type it pick a voice smartlink",
    audience: "podcasters",
    category: "grow",
  },
  {
    title: "Book a guest for your show",
    summary: "On your show's Book a guest tab: search, then Invite to my show, Find their email, or Save to Guests.",
    href: "/help/guests",
    keywords: "book a guest find guests invite to my show find their email save to guests discovery podchaser interview",
    audience: "podcasters",
    category: "grow",
  },
  {
    title: "Pitch yourself as a guest",
    summary: "On the Be a guest tab: find shows that take guests, then Write my pitch and send it from your own email.",
    href: "/help/guests#pitch",
    keywords: "be a guest pitch yourself write my pitch shows guest appearance open in my email",
    audience: "podcasters",
    category: "grow",
  },
  {
    title: "Saved guests and saved shows",
    summary: "At the top of Book a guest and Be a guest, switch between Search and your saved list.",
    href: "/help/guests#saved",
    keywords: "saved lists saved guests saved shows search shortlist take off the list discovery",
    audience: "podcasters",
    category: "grow",
  },
  {
    title: "Put back something you deleted",
    summary: "Recently deleted, in your account menu: 15 days to Put it back, or Delete now.",
    href: "/help/account#deleted",
    keywords: "recently deleted trash restore undelete put it back delete now 15 days lost deleted by mistake recover",
    audience: "podcasters",
    category: "account",
  },
  {
    title: "Plans and billing",
    summary: "Free, or a Pōstify plan with monthly credits. Upgrade, and Manage billing to change your card or cancel.",
    href: "/help/account#plans",
    keywords: "plan billing pricing upgrade creator pro subscription cancel card invoice manage billing stripe payment",
    audience: "podcasters",
    category: "account",
  },
  {
    title: "Credits",
    summary: "Credits pay for clips, clean episodes and contact emails past your monthly ones. Buy more in Plan & billing.",
    href: "/help/account#credits",
    keywords: "credits tokens buy credits top up cost contact email reveal 1 credit out of credits",
    audience: "podcasters",
    category: "account",
  },
  {
    title: "Discovery Pro",
    summary: "100 contact emails a month instead of 10. Add it in Plan & billing.",
    href: "/help/account#discovery",
    keywords: "discovery pro contact emails reveals look-ups lookups add-on upgrade discovery",
    audience: "podcasters",
    category: "account",
  },
  {
    title: "Sign in to your dashboard",
    summary: "Your email and a 6-digit code we send you. No password. Tick 'keep me signed in' on your own device.",
    href: "/host/dashboard",
    keywords: "sign in login code password email dashboard keep me signed in 30 days",
    audience: "podcasters",
    category: "lineup",
  },
  {
    title: "Pick or change your slot",
    summary: "Claim an open half-hour on the schedule, or move to another one from Event settings on your dashboard.",
    href: "/schedule",
    keywords: "slot time claim schedule change move release remove agenda when am I on",
    audience: "podcasters",
    category: "lineup",
  },
  {
    title: "Live, or a recorded episode",
    summary: "Go live from the green room in your window, or send us an episode you've already recorded and we roll it.",
    href: "/prepare",
    keywords: "pre-recorded prerecorded recorded episode upload file live format mp4 send us",
    audience: "podcasters",
    category: "showday",
  },
  {
    title: "The green room on show day",
    summary: "Where you wait with your camera on. Alex brings you to the stage when it's your turn. Be there 15 minutes early.",
    href: "/prepare",
    keywords: "green room studio camera mic show day on air stage producer alex call time",
    audience: "podcasters",
    category: "showday",
  },
  {
    title: "Co-host an hour with Riccoh or Alex",
    summary: "Take an hour on the main stage between shows. Pick it from Co-host Available Slots on your dashboard.",
    href: "/host/dashboard",
    keywords: "co-host cohost hour main stage riccoh alex between shows",
    audience: "podcasters",
    category: "showday",
  },
  {
    title: "Your photo and your card",
    summary: "A hi-res headshot, at least 1000 × 1000 pixels, and your show's details make your card on the lineup and the big screen.",
    href: "/host/dashboard",
    keywords: "photo headshot picture profile card lineup crop image hi-res high resolution size pixels blurry",
    audience: "podcasters",
    category: "lineup",
  },
  {
    title: "Connect your social accounts",
    summary: "Link the accounts you post from. They show as follow buttons on your card, and we post your promo cards for you.",
    href: "/host/dashboard",
    keywords: "social instagram tiktok facebook linkedin x threads connect accounts follow promo post upload-post",
    audience: "podcasters",
    category: "lineup",
  },
  {
    title: "Bring a sponsor to your segment",
    summary: "A sponsor on your segment is $250, and if you bring them you earn half. Bigger packages pay ten percent.",
    href: "/sponsors",
    keywords: "sponsor sponsorship money earn share package rev revenue bring",
    audience: "podcasters",
    category: "sponsors",
  },
  {
    title: "Recordings and clips after the show",
    summary: "Your segment's recording lands in your Library, ready for Pōstify to make clips and a clean episode.",
    href: "/help/library",
    keywords: "recording clips download after the show video shorts captions",
    audience: "podcasters",
    category: "showday",
  },
  {
    title: "What is The Podcast Marathon?",
    summary: "26.2 miles of stories: one day of military and veteran podcasts, back to back, live, for National Military Podcast Day.",
    href: "/faq",
    keywords: "what is marathon podcastathon national military podcast day event about",
    audience: "everyone",
    category: "watching",
  },
  {
    title: "When is it, and how do I watch?",
    summary: "Monday, October 5, 2026, from 7:00 AM Eastern. Watch on the site or on YouTube; the agenda has every show and time.",
    href: "/agenda",
    keywords: "when date time watch agenda schedule lineup october 5 listen",
    audience: "everyone",
    category: "watching",
  },
  {
    title: "Get a reminder for a show",
    summary: "Press Remind me on any card on the agenda and we'll email you before it starts.",
    href: "/agenda",
    keywords: "reminder remind me email notify before show starts",
    audience: "everyone",
    category: "watching",
  },
  {
    title: "Does it cost anything?",
    summary: "No. Watching is free, and podcasters take a slot for free.",
    href: "/faq",
    keywords: "cost free price pay charge fee",
    audience: "everyone",
    category: "watching",
  },
  {
    title: "What is the Podcast Marathon?",
    summary: "From the FAQ.",
    href: "/faq#what-is-the-podcast-marathon",
    keywords: "faq what is the podcast marathon?",
    audience: "everyone",
    category: "watching",
    faq: true,
  },
  {
    title: "When is it?",
    summary: "From the FAQ.",
    href: "/faq#when-is-it",
    keywords: "faq when is it?",
    audience: "everyone",
    category: "watching",
    faq: true,
  },
  {
    title: "Who is hosting?",
    summary: "From the FAQ.",
    href: "/faq#who-is-hosting",
    keywords: "faq who is hosting?",
    audience: "everyone",
    category: "watching",
    faq: true,
  },
  {
    title: "Does it cost anything?",
    summary: "From the FAQ.",
    href: "/faq#does-it-cost-anything",
    keywords: "faq does it cost anything?",
    audience: "everyone",
    category: "watching",
    faq: true,
  },
  {
    title: "Who can claim a slot?",
    summary: "From the FAQ.",
    href: "/faq#who-can-claim-a-slot",
    keywords: "faq who can claim a slot?",
    audience: "everyone",
    category: "lineup",
    faq: true,
  },
  {
    title: "How do I claim a slot?",
    summary: "From the FAQ.",
    href: "/faq#how-do-i-claim-a-slot",
    keywords: "faq how do i claim a slot?",
    audience: "everyone",
    category: "lineup",
    faq: true,
  },
  {
    title: "Do I need a password?",
    summary: "From the FAQ.",
    href: "/faq#do-i-need-a-password",
    keywords: "faq do i need a password?",
    audience: "everyone",
    category: "lineup",
    faq: true,
  },
  {
    title: "How long is a slot, and how much of it am I on the air?",
    summary: "From the FAQ.",
    href: "/faq#how-long-is-a-slot-and-how-much-of-it-am-i-on-the-air",
    keywords: "faq how long is a slot, and how much of it am i on the air?",
    audience: "everyone",
    category: "showday",
    faq: true,
  },
  {
    title: "Can I hold more than one slot?",
    summary: "From the FAQ.",
    href: "/faq#can-i-hold-more-than-one-slot",
    keywords: "faq can i hold more than one slot?",
    audience: "everyone",
    category: "lineup",
    faq: true,
  },
  {
    title: "Can I change or cancel my slot?",
    summary: "From the FAQ.",
    href: "/faq#can-i-change-or-cancel-my-slot",
    keywords: "faq can i change or cancel my slot?",
    audience: "everyone",
    category: "lineup",
    faq: true,
  },
  {
    title: "Can I play an episode I already recorded instead of going live?",
    summary: "From the FAQ.",
    href: "/faq#can-i-play-an-episode-i-already-recorded-instead-of-going-live",
    keywords: "faq can i play an episode i already recorded instead of going live?",
    audience: "everyone",
    category: "showday",
    faq: true,
  },
  {
    title: "Where do I broadcast from?",
    summary: "From the FAQ.",
    href: "/faq#where-do-i-broadcast-from",
    keywords: "faq where do i broadcast from?",
    audience: "everyone",
    category: "showday",
    faq: true,
  },
  {
    title: "Why do you ask for my RSS feed?",
    summary: "From the FAQ.",
    href: "/faq#why-do-you-ask-for-my-rss-feed",
    keywords: "faq why do you ask for my rss feed?",
    audience: "everyone",
    category: "lineup",
    faq: true,
  },
  {
    title: "What does connecting my social accounts do?",
    summary: "From the FAQ.",
    href: "/faq#what-does-connecting-my-social-accounts-do",
    keywords: "faq what does connecting my social accounts do?",
    audience: "everyone",
    category: "lineup",
    faq: true,
  },
  {
    title: "What should I have ready?",
    summary: "From the FAQ.",
    href: "/faq#what-should-i-have-ready",
    keywords: "faq what should i have ready?",
    audience: "everyone",
    category: "showday",
    faq: true,
  },
  {
    title: "Do listeners need to claim anything?",
    summary: "From the FAQ.",
    href: "/faq#do-listeners-need-to-claim-anything",
    keywords: "faq do listeners need to claim anything?",
    audience: "everyone",
    category: "watching",
    faq: true,
  },
  {
    title: "How do I know when a show I care about is starting?",
    summary: "From the FAQ.",
    href: "/faq#how-do-i-know-when-a-show-i-care-about-is-starting",
    keywords: "faq how do i know when a show i care about is starting?",
    audience: "everyone",
    category: "watching",
    faq: true,
  },
  {
    title: "Where do I watch or listen?",
    summary: "From the FAQ.",
    href: "/faq#where-do-i-watch-or-listen",
    keywords: "faq where do i watch or listen?",
    audience: "everyone",
    category: "watching",
    faq: true,
  },
  {
    title: "I'm overseas. Will the times make sense?",
    summary: "From the FAQ.",
    href: "/faq#i-m-overseas-will-the-times-make-sense",
    keywords: "faq i'm overseas. will the times make sense?",
    audience: "everyone",
    category: "watching",
    faq: true,
  },
  {
    title: "Can I share a show?",
    summary: "From the FAQ.",
    href: "/faq#can-i-share-a-show",
    keywords: "faq can i share a show?",
    audience: "everyone",
    category: "watching",
    faq: true,
  },
];

/** Rank entries against a query: title hits first, then keywords, then summary. */
export function searchHelp(query: string, audience?: HelpEntry["audience"]): HelpEntry[] {
  const q = query.trim().toLowerCase();
  const terms = q.split(/\s+/).filter((t) => t.length > 1);
  const pool = audience ? HELP_INDEX.filter((e) => e.audience === audience || e.audience === "everyone") : HELP_INDEX;
  if (terms.length === 0) return pool;
  return pool
    .map((e) => {
      const title = e.title.toLowerCase();
      const kw = e.keywords.toLowerCase();
      const sum = e.summary.toLowerCase();
      let score = 0;
      for (const t of terms) {
        if (title.includes(t)) score += 5;
        if (kw.includes(t)) score += 3;
        if (sum.includes(t)) score += 1;
      }
      return { e, score };
    })
    .filter((x) => x.score > 0)
    .sort((a, b) => b.score - a.score)
    .map((x) => x.e);
}
