// A side-by-side test of Creatomate as the clip renderer.
//
// Our clipper renders with ffmpeg on a machine someone has to keep running.
// Creatomate renders in the cloud from a JSON description. This sends one clip
// we already made (same moment, same source) to Creatomate in the three shapes,
// with its own word-by-word captions, so the two can be compared before
// anything is switched over. Admin only; nothing here touches the real clips.

import type { Express } from "express";
import { storage } from "./storage.js";
import { signedRecordingUrl } from "./recordingStorage.js";

const API = "https://api.creatomate.com/v1/renders";
// Accepts the obvious spellings, since the key is typed into Vercel by hand.
const key = () =>
  (process.env.CREATOMATE_API_KEY || process.env.CREATOMATE_KEY || process.env.CREATOMATE_API || process.env.CREATOMATE || "").trim();

type Shape = "vertical" | "square" | "wide";
const SIZE: Record<Shape, [number, number]> = { vertical: [1080, 1920], square: [1080, 1080], wide: [1920, 1080] };

function source(shape: Shape, videoUrl: string, start: number, length: number, title: string, show: string) {
  const [w, h] = SIZE[shape];
  const banded = shape !== "wide";
  return {
    output_format: "mp4",
    width: w,
    height: h,
    frame_rate: 30,
    duration: length,
    elements: [
      // The picture over a blurred copy of itself — never cropped, like our clipper.
      { type: "video", source: videoUrl, trim_start: start, trim_duration: length, fit: "cover", blur_radius: 40, volume: "0%", track: 1 },
      { name: "Main", type: "video", source: videoUrl, trim_start: start, trim_duration: length, fit: "contain", track: 2, ...(banded ? { y: "52%", height: "70%" } : {}) },
      ...(banded
        ? [
            { type: "shape", track: 3, y: "8%", width: "100%", height: "16%", fill_color: "#000741", path: "M 0 0 L 100 0 L 100 100 L 0 100 Z" },
            { type: "text", track: 4, text: show.toUpperCase(), y: "4.5%", width: "90%", height: "4%", font_family: "Montserrat", font_weight: "800", fill_color: "#F0A71F", x_alignment: "50%", y_alignment: "50%", font_size: "3.2 vmin" },
            { type: "text", track: 5, text: title, y: "10%", width: "90%", height: "7%", font_family: "Montserrat", font_weight: "700", fill_color: "#ffffff", x_alignment: "50%", y_alignment: "50%", font_size: "4.6 vmin" },
          ]
        : []),
      // Word-by-word captions, generated by Creatomate from the Main video's audio.
      {
        type: "text",
        track: 6,
        transcript_source: "Main",
        transcript_effect: "highlight",
        transcript_maximum_length: 24,
        transcript_color: "#F0A71F",
        y: shape === "wide" ? "82%" : "84%",
        width: "86%",
        height: "14%",
        x_alignment: "50%",
        y_alignment: "50%",
        fill_color: "#ffffff",
        stroke_color: "#000000",
        stroke_width: "1.2 vmin",
        font_family: "Montserrat",
        font_weight: "800",
        font_size: shape === "wide" ? "6 vmin" : "7 vmin",
      },
    ],
  };
}

export function registerCreatomate(app: Express, requireAdmin: any): void {
  /** Render one existing clip through Creatomate in all three shapes. Returns the render ids. */
  app.post("/api/admin/creatomate/test", requireAdmin, async (req, res) => {
    if (!key()) return res.status(503).json({ message: "CREATOMATE_API_KEY isn't set." });
    const clipId = Number(req.body?.clipId);
    const clip = (await storage.listClips(Number(req.body?.recordingId) || 0)).find((c) => c.id === clipId);
    if (!clip) return res.status(404).json({ message: "No such clip on that recording." });
    const rec = await storage.getRecording(clip.recordingId);
    if (!rec?.url) return res.status(404).json({ message: "The recording has no file." });
    const videoUrl = /^https?:\/\//i.test(rec.url) ? rec.url : await signedRecordingUrl(rec.url, 6 * 3600);
    const signup = rec.signupId ? await storage.getSignupById(rec.signupId) : undefined;
    const show = signup?.podcastName || rec.title || "MilitaryVoices";
    const length = clip.endSec - clip.startSec;
    const shapes: Shape[] = Array.isArray(req.body?.shapes) ? req.body.shapes.filter((s: string) => s in SIZE) : ["vertical", "square", "wide"];
    const out: Record<string, unknown>[] = [];
    for (const shape of shapes) {
      const r = await fetch(API, {
        method: "POST",
        headers: { Authorization: `Bearer ${key()}`, "Content-Type": "application/json" },
        body: JSON.stringify({ source: source(shape, videoUrl, clip.startSec, length, clip.title, show) }),
      });
      const j = await r.json().catch(() => null);
      out.push({ shape, status: r.status, result: j });
    }
    res.json({ clip: { id: clip.id, title: clip.title, startSec: clip.startSec, endSec: clip.endSec, verticalUrl: clip.verticalUrl, squareUrl: clip.squareUrl, url: clip.url }, renders: out });
  });

  /** Which Creatomate-looking settings this deployment can see — names only, never values. */
  app.get("/api/admin/creatomate/env", requireAdmin, (_req, res) => {
    res.json({ names: Object.keys(process.env).filter((k) => /creat/i.test(k)), usable: Boolean(key()), env: process.env.VERCEL_ENV ?? "" });
  });

  /** Where a test render has got to. */
  app.get("/api/admin/creatomate/renders/:id", requireAdmin, async (req, res) => {
    if (!key()) return res.status(503).json({ message: "CREATOMATE_API_KEY isn't set." });
    const r = await fetch(`${API}/${encodeURIComponent(String(req.params.id))}`, { headers: { Authorization: `Bearer ${key()}` } });
    res.status(r.status).json(await r.json().catch(() => null));
  });
}
