// A side-by-side test of Creatomate as the clip renderer.
//
// Our clipper renders with ffmpeg on a machine someone has to keep running.
// Creatomate renders in the cloud from a JSON description. This sends one clip
// we already made (same moment, same source) to Creatomate in the three shapes,
// with its own word-by-word captions, so the two can be compared before
// anything is switched over. Admin only; nothing here touches the real clips.

import type { Express } from "express";
import { storage } from "./storage.js";
import { signedRecordingUrl } from "./recordingStorage.js";

const API = "https://api.creatomate.com/v1/renders";
// Accepts the obvious spellings, since the key is typed into Vercel by hand.
const key = () =>
  (process.env.CREATOMATE_API_KEY || process.env.CREATOMTE_API_KEY || process.env.CREATOMATE_KEY || process.env.CREATOMATE_API || process.env.CREATOMATE || "").trim();

type Shape = "vertical" | "square" | "wide";
const SIZE: Record<Shape, [number, number]> = { vertical: [1080, 1920], square: [1080, 1080], wide: [1920, 1080] };

function source(shape: Shape, videoUrl: string, start: number, length: number, title: string, show: string, scale = 1) {
  const [w, h] = SIZE[shape].map((n) => Math.round((n * scale) / 2) * 2) as [number, number];
  const banded = shape !== "wide";
  return {
    output_format: "mp4",
    width: w,
    height: h,
    frame_rate: scale < 1 ? 25 : 30,
    duration: length,
    elements: [
      // The picture over a blurred copy of itself — never cropped, like our clipper.
      { type: "video", source: videoUrl, trim_start: start, trim_duration: length, fit: "cover", blur_radius: 40, volume: "0%", track: 1 },
      { name: "Main", type: "video", source: videoUrl, trim_start: start, trim_duration: length, fit: "contain", track: 2, ...(banded ? { y: "52%", height: "70%" } : {}) },
      ...(banded
        ? [
            { type: "shape", track: 3, y: "8%", width: "100%", height: "16%", fill_color: "#000741", path: "M 0 0 L 100 0 L 100 100 L 0 100 Z" },
            { type: "text", track: 4, text: show.toUpperCase(), y: "4.5%", width: "90%", height: "4%", font_family: "Montserrat", font_weight: "800", fill_color: "#F0A71F", x_alignment: "50%", y_alignment: "50%", font_size: "3.2 vmin" },
            { type: "text", track: 5, text: title, y: "10%", width: "90%", height: "7%", font_family: "Montserrat", font_weight: "700", fill_color: "#ffffff", x_alignment: "50%", y_alignment: "50%", font_size: "4.6 vmin" },
          ]
        : []),
      // Word-by-word captions, generated by Creatomate from the Main video's audio.
      {
        type: "text",
        track: 6,
        transcript_source: "Main",
        transcript_effect: "highlight",
        transcript_maximum_length: 24,
        transcript_color: "#F0A71F",
        y: shape === "wide" ? "82%" : "84%",
        width: "86%",
        height: "14%",
        x_alignment: "50%",
        y_alignment: "50%",
        fill_color: "#ffffff",
        stroke_color: "#000000",
        stroke_width: "1.2 vmin",
        font_family: "Montserrat",
        font_weight: "800",
        font_size: shape === "wide" ? "6 vmin" : "7 vmin",
      },
    ],
  };
}

// ---------------------------------------------------------------------------
// The combined version: our layout, Creatomate's rendering and captions.
// ---------------------------------------------------------------------------
// The clipper still decides the framing — where the picture really is inside
// the file, and whether it's two people side by side (then each gets their own
// full-width panel, stacked). Creatomate draws that, adds our title band, and
// writes word-by-word captions from the audio. Everything is placed in
// percentages of its parent, so no unit guessing.

export interface Box { w: number; h: number; x: number; y: number }
export interface Geo { srcW: number; srcH: number; whole: Box | null; left: Box | null; right: Box | null; stack: boolean }

const pct = (n: number) => `${Math.round(n * 10000) / 100}%`;

/** A panel showing one rectangle of the source, scaled to cover the panel and clipped to it. */
function panel(videoUrl: string, start: number, length: number, geo: Geo, tile: Box, box: { x: number; y: number; w: number; h: number }, canvas: [number, number], track: number) {
  const [W, H] = canvas;
  const PW = box.w * W, PH = box.h * H;
  const s = Math.max(PW / tile.w, PH / tile.h);
  const vw = geo.srcW * s, vh = geo.srcH * s;
  const cx = PW / 2 + (geo.srcW / 2 - (tile.x + tile.w / 2)) * s;
  const cy = PH / 2 + (geo.srcH / 2 - (tile.y + tile.h / 2)) * s;
  return {
    type: "composition",
    track,
    x: pct(box.x + box.w / 2),
    y: pct(box.y + box.h / 2),
    width: pct(box.w),
    height: pct(box.h),
    clip: true,
    elements: [
      { type: "video", source: videoUrl, trim_start: start, trim_duration: length, volume: "0%", x: pct(cx / PW), y: pct(cy / PH), width: pct(vw / PW), height: pct(vh / PH), fit: "fill" },
    ],
  };
}

export function combinedSource(o: {
  shape: Shape; videoUrl: string; start: number; length: number; title: string; show: string; geo: Geo; captionColor?: string;
}) {
  const [W, H] = SIZE[o.shape];
  const banded = o.shape !== "wide";
  const band = banded ? 220 / H : 0;
  const els: Record<string, unknown>[] = [];
  const whole = o.geo.whole ?? { x: 0, y: 0, w: o.geo.srcW, h: o.geo.srcH };
  // The sound, once, and the thing the captions listen to.
  els.push({ name: "Voice", type: "audio", source: o.videoUrl, trim_start: o.start, trim_duration: o.length, track: 1 });
  if (banded && o.geo.stack && o.geo.left && o.geo.right) {
    const h = (1 - band) / 2;
    els.push(panel(o.videoUrl, o.start, o.length, o.geo, o.geo.left, { x: 0, y: band, w: 1, h }, [W, H], 2));
    els.push(panel(o.videoUrl, o.start, o.length, o.geo, o.geo.right, { x: 0, y: band + h, w: 1, h }, [W, H], 3));
  } else {
    // One picture: the real picture (not the file's letterbox) over a blurred
    // copy of itself, whole — a room of people keeps all its people.
    const area = { x: 0, y: band, w: 1, h: 1 - band };
    const blurred = panel(o.videoUrl, o.start, o.length, o.geo, whole, area, [W, H], 2);
    blurred.elements = blurred.elements.map((v) => ({ ...v, blur_radius: 30 }));
    els.push(blurred);
    const fitW = area.w * W, fitH = area.h * H;
    const s = Math.min(fitW / whole.w, fitH / whole.h);
    const bw = (whole.w * s) / W, bh = (whole.h * s) / H;
    els.push(panel(o.videoUrl, o.start, o.length, o.geo, whole, { x: (1 - bw) / 2, y: band + (area.h - bh) / 2, w: bw, h: bh }, [W, H], 3));
  }
  if (banded) {
    els.push({ type: "shape", track: 4, x: "50%", y: pct(band / 2), width: "100%", height: pct(band), fill_color: "#000741", path: "M 0 0 L 100 0 L 100 100 L 0 100 Z" });
    els.push({ type: "text", track: 5, text: o.title, x: "50%", y: pct(band * 0.4), width: "92%", height: pct(band * 0.5), x_alignment: "50%", y_alignment: "50%", font_family: "Montserrat", font_weight: "800", fill_color: "#ffffff", font_size_maximum: "6.2 vmin", font_size_minimum: "3 vmin" });
    els.push({ type: "text", track: 6, text: o.show.toUpperCase(), x: "50%", y: pct(band * 0.8), width: "92%", height: pct(band * 0.22), x_alignment: "50%", y_alignment: "50%", font_family: "Montserrat", font_weight: "700", letter_spacing: "8%", fill_color: "#F0A71F", font_size_maximum: "3 vmin", font_size_minimum: "2 vmin" });
  }
  els.push({
    type: "text",
    track: 7,
    transcript_source: "Voice",
    transcript_effect: "highlight",
    transcript_maximum_length: 22,
    transcript_color: o.captionColor ?? "#F0A71F",
    x: "50%",
    y: o.shape === "wide" ? "84%" : o.shape === "square" ? "86%" : "82%",
    width: "86%",
    height: "14%",
    x_alignment: "50%",
    y_alignment: "50%",
    fill_color: "#ffffff",
    stroke_color: "#000000",
    stroke_width: "1.1 vmin",
    font_family: "Montserrat",
    font_weight: "800",
    font_size: o.shape === "wide" ? "5.4 vmin" : "6.6 vmin",
  });
  return { output_format: "mp4", width: W, height: H, frame_rate: 30, duration: o.length, elements: els };
}

export function registerCreatomate(app: Express, requireAdmin: any, requireAgent?: any): void {
  if (requireAgent) {
    /**
     * The clipper's renderer. It sends one moment with the framing it measured;
     * we hold the key, start the three renders and hand back their ids. 503
     * when there's no key, which the worker reads as "render it yourself".
     */
    app.post("/api/agent/clip-renders", requireAgent, async (req, res) => {
      if (!key()) return res.status(503).json({ message: "No Creatomate key." });
      const b = req.body ?? {};
      const shapes: Shape[] = Array.isArray(b.shapes) ? b.shapes.filter((x: string) => x in SIZE) : ["vertical", "square", "wide"];
      const out: { shape: Shape; id: string }[] = [];
      for (const shape of shapes) {
        const src = combinedSource({ shape, videoUrl: String(b.videoUrl), start: Number(b.start), length: Number(b.length), title: String(b.title ?? ""), show: String(b.show ?? ""), geo: b.geo as Geo });
        const r = await fetch(API, { method: "POST", headers: { Authorization: `Bearer ${key()}`, "Content-Type": "application/json" }, body: JSON.stringify({ source: src }) });
        const j = await r.json().catch(() => null);
        const id = Array.isArray(j) ? j[0]?.id : null;
        if (!r.ok || !id) return res.status(502).json({ message: `Creatomate refused the ${shape} render: ${JSON.stringify(j).slice(0, 200)}` });
        out.push({ shape, id });
      }
      res.json({ renders: out });
    });

    app.get("/api/agent/clip-renders/:id", requireAgent, async (req, res) => {
      if (!key()) return res.status(503).json({ message: "No Creatomate key." });
      const r = await fetch(`${API}/${encodeURIComponent(String(req.params.id))}`, { headers: { Authorization: `Bearer ${key()}` } });
      const j = (await r.json().catch(() => null)) as { status?: string; url?: string; error_message?: string } | null;
      res.status(r.ok ? 200 : r.status).json({ status: j?.status ?? "unknown", url: j?.url ?? "", error: j?.error_message ?? "" });
    });
  }

  /** Render one existing clip through Creatomate in all three shapes. Returns the render ids. */
  app.post("/api/admin/creatomate/test", requireAdmin, async (req, res) => {
    if (!key()) return res.status(503).json({ message: "CREATOMATE_API_KEY isn't set." });
    const clipId = Number(req.body?.clipId);
    const clip = (await storage.listClips(Number(req.body?.recordingId) || 0)).find((c) => c.id === clipId);
    if (!clip) return res.status(404).json({ message: "No such clip on that recording." });
    const rec = await storage.getRecording(clip.recordingId);
    if (!rec?.url) return res.status(404).json({ message: "The recording has no file." });
    const videoUrl = /^https?:\/\//i.test(rec.url) ? rec.url : await signedRecordingUrl(rec.url, 6 * 3600);
    const signup = rec.signupId ? await storage.getSignupById(rec.signupId) : undefined;
    const show = signup?.podcastName || rec.title || "MilitaryVoices";
    // A cheap draft while trying it out: smaller frame, a few seconds.
    const scale = Math.min(1, Math.max(0.3, Number(req.body?.scale) || 1));
    const length = Math.min(clip.endSec - clip.startSec, Number(req.body?.maxSeconds) || Infinity);
    const shapes: Shape[] = Array.isArray(req.body?.shapes) ? req.body.shapes.filter((s: string) => s in SIZE) : ["vertical", "square", "wide"];
    const out: Record<string, unknown>[] = [];
    for (const shape of shapes) {
      const r = await fetch(API, {
        method: "POST",
        headers: { Authorization: `Bearer ${key()}`, "Content-Type": "application/json" },
        body: JSON.stringify({ source: source(shape, videoUrl, clip.startSec, length, clip.title, show, scale) }),
      });
      const j = await r.json().catch(() => null);
      out.push({ shape, status: r.status, result: j });
    }
    res.json({ clip: { id: clip.id, title: clip.title, startSec: clip.startSec, endSec: clip.endSec, verticalUrl: clip.verticalUrl, squareUrl: clip.squareUrl, url: clip.url }, renders: out });
  });

  /** Which Creatomate-looking settings this deployment can see — names only, never values. */
  app.get("/api/admin/creatomate/env", requireAdmin, (_req, res) => {
    res.json({ names: Object.keys(process.env).filter((k) => /creat/i.test(k)), usable: Boolean(key()), env: process.env.VERCEL_ENV ?? "" });
  });

  /** The combined version: our framing (geo, measured by the clipper), Creatomate's render and captions. */
  app.post("/api/admin/creatomate/combined", requireAdmin, async (req, res) => {
    if (!key()) return res.status(503).json({ message: "The Creatomate key isn't set." });
    const b = req.body ?? {};
    const shapes: Shape[] = Array.isArray(b.shapes) ? b.shapes.filter((x: string) => x in SIZE) : ["vertical", "square", "wide"];
    const out: Record<string, unknown>[] = [];
    for (const shape of shapes) {
      const src = combinedSource({ shape, videoUrl: String(b.videoUrl), start: Number(b.start), length: Number(b.length), title: String(b.title ?? ""), show: String(b.show ?? ""), geo: b.geo as Geo });
      const r = await fetch(API, { method: "POST", headers: { Authorization: `Bearer ${key()}`, "Content-Type": "application/json" }, body: JSON.stringify({ source: src }) });
      out.push({ shape, status: r.status, result: await r.json().catch(() => null) });
    }
    res.json({ renders: out });
  });

  /** Where a test render has got to. */
  app.get("/api/admin/creatomate/renders/:id", requireAdmin, async (req, res) => {
    if (!key()) return res.status(503).json({ message: "CREATOMATE_API_KEY isn't set." });
    const r = await fetch(`${API}/${encodeURIComponent(String(req.params.id))}`, { headers: { Authorization: `Bearer ${key()}` } });
    res.status(r.status).json(await r.json().catch(() => null));
  });
}
