// Generated by scripts/build-help-kb.mjs from the live help articles, FAQ and podcaster guide.
// Don't edit by hand: change the article, deploy, and re-run the script.
export const HELP_ARTICLES = `
=== MILITARYVOICES.AI PLATFORM · www.militaryvoices.ai/help/rooms ===
All help Help · Rooms
Your room: record and go live with guests
Rooms is quick, like Zoom. Hop in any time and bring guests on a link. Record it or don't. Go live if you like. What you record lands in your Library, ready for Pōstify.
1 Go into your room
a Sign in to your dashboard and press Rooms in the menu.
b Press Enter my room. Your room opens in its own page.
c Check your camera and microphone. Pick the ones you want, and check Your name.
d Press Enter my room again. You're in.
Inside, you can see everyone as a grid or the speaker big, share your screen, and chat.
No picture or sound? Your browser needs your OK. Press the camera icon in the address bar, allow the camera and microphone for this site, then reload the page.
When you leave, you'll see You've left your room. Press Go back in, or Your Library to see what you recorded.
2 Invite a guest
Your room has one invite link. Guests don't need an account. They open the link, type their name, and come straight in.
a On the Rooms screen, under Invite a guest, press Copy link. In the room, press Invite a guest at the top. Both copy the same link.
b Send it to your guest by text or email.
c They check their camera and mic, type their name and press Join.
Want a fresh link?
Press New link on the Rooms screen. The old link stops working at once. Anyone who opens it is told to ask you for a new one.
3 Record
a In your room, press Record at the top. A red REC timer shows it's running. Everyone in the room sees it.
b Press Stop recording when you're done.
c It's in your Library in a minute or two, named after your show and the date. From there, Pōstify makes the clips and a clean episode.
The recorder needs at least one camera on. If it doesn't start, turn a camera on and press Record again.
4 Go live
Go live streams your room to everywhere switched on under When you go live on the Rooms screen, all at once.
a On the Rooms screen, check YouTube is switched on. Each time you go live, it makes a new live video on your channel. Not connected yet? Press Connect YouTube.
b In your room, press Go live. A red LIVE timer shows you're on. Press Watch on YouTube to see what your audience sees.
c Press End live to stop. You can record and be live at the same time.
Turn on live streaming first
YouTube has to switch on live streaming for your channel before anyone can stream to it. In YouTube Studio, press Create, then Go live. YouTube asks for a phone number, and the first time can take up to a day. Do it before your first show, not on the day.
If it isn't on yet, your room says so. You can still go live on a streaming key while you wait.
5 Streaming keys
Go live on Facebook, LinkedIn, Twitch, Kick and most others with a streaming key. Each gives you a server address and a key in its "Live" or "Stream" settings.
a On the Rooms screen, press Add a streaming key.
b Type a name (like Facebook), paste the Server (it starts rtmp:// or rtmps://) and the Stream key, then press Add.
c Use its switch to turn it on or off for your next Go live. The bin removes it.
You can add up to six. Go live needs at least one place to go: YouTube or a key.
6 Rooms or Studio?
Rooms is here now: quick, with guests on a link, record, go live.
Studio is the full marathon studio for your own show: scenes, layouts, lower thirds and a producer console. It's coming October 5. Until then, Rooms covers recording and going live.
On Marathon day, your slot goes out from the green room, not your room. See the podcaster guide.
7 Help and contact
Email us: hello@militaryvoices.ai. A person reads every message and writes back.
Search the help, or ask Alex: militaryvoices.ai/help.
Your invite link and where going live goes are on the Rooms screen.
Open Rooms

=== MILITARYVOICES.AI PLATFORM · www.militaryvoices.ai/help/library ===
All help Help · Your Library
Your Library: every episode and every clip
Everything you record or upload lands in your Library: your room's recordings, your Marathon slot, videos you upload, Zoom calls, and the clean and edited episodes Pōstify makes. Your clips live here too.
1 The counts at the top
Press Library in the menu. Across the top you'll see your Library at a glance. The ones with an arrow are buttons:
Episodes → shows your episodes.
Clips made → shows every clip.
Posts sent → opens your calendar on the Social screen.
Hours recorded and Time saved (what Pōstify took out of your clean episodes) are just to know.
To add a video, drop it on the upload box beside them. Record on Zoom? Connect Zoom and your recordings come in by themselves. See Zoom recordings.
2 Episodes and Clips
Two tabs show the same Library two ways: Episodes and Clips, each with how many.
Episodes: each episode as a card. A badge says Clips ready or Clean episode when Pōstify has made them.
Under an episode's name, 4 clips → (or however many) opens the Clips tab with just that episode's clips.
Clips: every clip, newest first, with the episode it came from. Use the box at the top to see All episodes or one.
3 Clean, Edited, Original
Once Pōstify has worked on an episode, its card has a switch with each version:
Clean: ums, false starts and dead air taken out.
Edited: your latest edit from Pōstify, with your trims, cuts, music, intro and outro. It shows first when there is one.
Original: the episode as it was recorded. Nothing ever changes it.
Made more than one edit? The ones before your latest wait under Earlier edits, each by when you made it. Pick one to play it or download it.
4 What you can do with an episode
Press ⋯ on an episode's card. What you do applies to the version showing.
Download the version you're looking at.
Pōstify it makes clips and a clean episode. Once made, it reads Clips in Pōstify. See Pōstify help.
Rename it.
Add to my podcast makes it an episode of your show. Nothing goes to your podcast until you do this. No show yet? It reads Start my podcast.
Post it sends the whole episode to YouTube. Other apps get its clips (see below).
Move to folder, or make a New folder….
Delete, for uploads, Zoom imports and Pōstify's copies.
A whole episode goes to YouTube only. For Instagram, TikTok, Facebook and LinkedIn, post its clips: short videos do better there, and Instagram only takes videos up to 15 minutes.
5 Scheduled or Posted
On the Clips tab, each clip shows where it stands:
Scheduled (navy): waiting in your queue to go out.
Posted (green): it's out.
No badge: ready, not posted yet.
Each clip card works just like in Pōstify. Press Post to send it, or ⋯ to download it, copy its caption, trim it, edit its title, or delete it.
6 Deleting
a Press ⋯, then Delete. It's there for videos you uploaded or brought in from Zoom, and for Pōstify's copies.
b Deleting an episode takes its clean copy and its clips with it. They move to Recently deleted.
c Changed your mind? You have 15 days to put it back. See Recently deleted.
Deleting one version (a clean or edited copy) leaves the original and its clips alone.
7 Help and contact
Email us: hello@militaryvoices.ai. A person reads every message and writes back.
Search the help, or ask Alex: militaryvoices.ai/help.
Your episodes, clips and versions are all in your Library.
Open my Library

=== MILITARYVOICES.AI PLATFORM · www.militaryvoices.ai/help/postify ===
All help Help · Pōstify
Edit your episode and clips in Pōstify
Pōstify makes short clips from your video and a clean episode with the ums and dead air taken out. You can also edit the episode yourself: trim the ends, take out a section, add music, an intro and an outro. Your original is never changed.
1 Open an episode
a Press Pōstify in the menu. Under Pick an episode, choose one.
b Not clipped yet? Press the wand, Start Pōstify, for clips and a clean episode. Once it's done, the pencil on the card goes straight to Edit episode.
c At the top, choose Edit episode or Make a clip. With a clean episode, pick Clean or Original to work from.
You can also start from your Library: press ⋯ on an episode, then Pōstify it or Clips in Pōstify.
2 Trim the start and end
Trim only cuts the beginning and the end: the chat before you start, and after you sign off.
a Press Trim start & end (the bracket icon) under the player.
b Yellow handles appear at each end of the timeline. Drag the left one to where the show should begin, and the right one to where it should end. The player shows that frame as you drag.
c Press Done.
For a precise cut, zoom in on the timeline. Click a handle and the arrow keys move it a second at a time (five with Shift).
3 Take out a section
Split takes out a part in the middle: a false start, a phone call, a tech check.
a Move the blue playhead to where the part starts. Press Split (the scissors), or the Split that pops up beside the playhead. The S key works too.
b Move the playhead to where the part ends, and Split again.
c It says Now click the piece to take out. Click the piece between your two splits. It's outlined, with a red Delete on it.
d Press Delete, or the yellow Take out … · Done button. Either one takes it out.
The Length beside the buttons shows how long the episode will be.
Let SI find them
Press the sparkle, Suggest edits. SI listens to the episode and marks tech checks, restarts and interruptions. You decide: Accept, Dismiss, or Accept all.
4 Your edits and drafts
Under the timeline, Your edits lists what you've done in plain words, like "16 sec trimmed from the beginning" or "11 sec taken out at 12:40", with the length before and after.
Click an edit to play from there.
Press its ✕ to undo just that one. Undo all starts over.
Your work saves as you go. You'll see Draft saved.
Save & close keeps your edits and takes you to your Library. Open the episode again to carry on where you left off. Nothing is made yet.
5 Save to Library
a When your edits are done, press Save to Library.
b It takes a few minutes. You can close the page; it keeps going.
c It lands in your Library as a new copy, Edited, next to your original. The original isn't touched.
Nothing goes to your podcast yet. When you're happy with it, press ⋯ on it in your Library and choose Add to my podcast.
6 Music for the episode
Our own tracks, cleared for podcasts and YouTube.
a In Edit episode, press Music at the bottom.
b Where: The opening (first 30 seconds), The close (last 30 seconds), The piece I picked (split, then click a piece first), or The whole episode (quietly, all the way through).
c How loud: Under the voices (soft, while people talk), or Full (for a part with no talking).
d Press play to hear a Track, pick one, then press Add.
It shows in Your edits, where you can undo it. It's mixed in when you save to your Library. Add more than one if you like: one for the opening, another for the close.
7 Intro and outro
a At the left end of the timeline, press Intro. At the right end, Outro. Pick a short video (under 500MB).
b The round button where it meets the episode sets the join: Fade, Dip to black or Cut.
c To take one off, press the ✕ on it.
We remember them for your next episode. The player shows the episode only; the intro and outro are in the copy you save.
8 Your clips
Pōstify picks the best moments and makes each clip in vertical, square and wide. To make your own, choose Make a clip, press Start here and End here, name it, pick its shapes, and press Make clip.
Press ⋯ on any clip (in Pōstify or your Library's Clips tab):
Trim this clip
Play it. Press Start here and End here at the right moments, or use the sliders. It has to be at least 5 seconds. Press Play the new version to check, then Trim the clip. Every shape is remade in about a minute.
Edit the title and text
Change the Title (the headline across the top; six words or so reads best) and the Subtitle (the smaller gold line). Stuck? Press Suggest titles for three ideas from what's said in the clip, and click one to use it. Then press Update clip.
Your clip's music stays when it's remade after a trim or new text.
The same menu has downloads for each shape, Download subtitles (.srt), Copy the caption and Delete this clip.
9 Posting
Clips go anywhere: Instagram, TikTok, Facebook, LinkedIn, YouTube. Press Post on a clip, tick the accounts, pick the shape, write what to say, and choose Next open slot, Now or Pick a time.
A whole episode goes to YouTube only. Instagram takes videos up to 15 minutes, and short videos do better on the other apps. So for Instagram, TikTok, Facebook and LinkedIn, post the episode's clips: Choose clips to post → takes you to them.
Nothing goes out until you press the button. Everything you've sent or scheduled is on the Social calendar.
Your podcast can post episodes to YouTube too. See your episodes on YouTube.
10 Help and contact
Email us: hello@militaryvoices.ai. A person reads every message and writes back.
Search the help, or ask Alex: militaryvoices.ai/help.
Pick an episode to edit, or see the clips Pōstify made.
Open Pōstify

=== MILITARYVOICES.AI PLATFORM · www.militaryvoices.ai/help/podcast ===
All help Help · Your podcast
Your podcast in Apple Podcasts, Spotify and every app
When you host your show here, MilitaryVoices.ai keeps its feed: one web address, listed in your Podcast screen, that every app reads. You give it to Apple and Spotify once. After that, each new episode you publish reaches them on its own, usually within the hour.
1 How it reaches the apps
Podcast apps don't take uploads. They read your show's RSS feed, a list of your episodes that we publish at an address like militaryvoices.ai/feed/your-show. You'll find yours at the top of your Podcast screen; press it to copy it.
Apple Podcasts and Spotify each need you to submit the feed once, in their own sites (steps below).
Most other apps (Overcast, Pocket Casts, Castro, Podcast Addict and more) find your show through Apple's directory by themselves.
From then on, publish on MilitaryVoices and every app picks the episode up. Nothing to send again.
Every play is counted here as a download, once per listener a day with bots left out: the way sponsors count.
2 Before the apps will take it
Apple and Spotify turn a feed away if it's missing any of these. The yellow box on your Podcast screen lists what's left; tap an item and it takes you to where you add it.
A show name and a description of a sentence or two: what it's about, who it's for, who hosts it. Show details → Description.
Cover art: a square JPG or PNG, 1400 to 3000 pixels on a side. Press the cover art square to add it.
An owner email, confirmed with the 6-digit code we send it. Apple and Spotify send their own confirmation there.
A category, in Show details.
One published episode. New episode → upload the audio (or pick a clean episode from your Library) → Publish.
3 Listing your show
Apple Podcasts
a On your Podcast screen, open your show's Directories tab. When the list at the top is done, press List it beside Apple Podcasts: your feed is copied and Apple's page opens. Sign in with your Apple ID.
b Choose to add a new show with an RSS feed, and paste your feed address.
c Check the details and submit. Apple reviews it, usually within a few days, and emails the owner email.
d Once it's live, paste your show's Apple link under Apple Podcasts in Directories and press It's live, so your page and SmartLink link to it.
Spotify
a Press List it beside Spotify in Directories (or go to creators.spotify.com) and sign in.
b Choose to add a podcast you already host somewhere else, and paste your feed address.
c Spotify emails a code to your owner email. Enter it, check the details, and submit. It's usually live within hours.
d Paste the Spotify link under Spotify in Directories and press It's live. YouTube Music, Amazon Music, iHeartRadio, Pocket Casts and Podcast Index are listed there the same way.
4 Your episodes on YouTube
An episode made from a video (an MP4 you upload, or a Library recording) can go to your YouTube channel too, with its title, notes and picture. Connect your channel once on the Social screen.
Choose once, for each show
a Open your show on the Podcast screen. Find Your episodes as videos on YouTube.
b Under When I publish an episode with video, pick Ask me each time or Always post it to YouTube.
c Pick Public or Unlisted (only people with the link can see it). We remember both.
When you publish
The publish window has an Also post it to YouTube box, ticked for you on Always. Leave it ticked to post it, or untick it. An episode set for later goes to YouTube when it goes out.
The YouTube list
Each video episode says where it stands: on YouTube, going when it's out, not on YouTube, or why it didn't post.
Post now sends one that isn't there yet.
Not this one keeps an episode off YouTube, even on Always. Undo brings it back.
Never the same video twice
Your Library and your podcast know about each other. If you already posted a recording to YouTube from your Library, publishing it as a podcast episode won't post it again, and the publish window tells you when it went. It works the other way too. Want it there twice on purpose? Post again asks you first.
5 Taking it down
The apps keep a show listed for as long as they can read its feed, so take it down in the apps first, then here.
Apple Podcasts: in Podcasts Connect, open your show and remove it from Apple Podcasts. It disappears within about a day.
Spotify: in Spotify for Creators, open your show's settings and remove it from Spotify, or ask Spotify's support to.
Here: on your Podcast screen, Delete this show. Its feed stops, so any app still reading it drops the show.
Just want one episode gone? Open it on your Podcast screen and press Delete. It leaves your feed, and the apps drop it the next time they check. Deleting it here doesn't take it off YouTube; remove it in YouTube Studio if you posted it there.
Deleted the wrong one? An episode, or a whole show with its episodes, waits in Recently deleted in your account menu for 15 days. Put it back and it returns as the same episode, in your feed again. See Recently deleted.
6 Moving hosts (the 301)
Your listeners follow your feed's address. When a show moves, the old address has to forward to the new one with a 301 redirect, so every app moves over by itself and nobody has to subscribe again.
Moving your show here
a On your Podcast screen, paste your current feed address to import the show. Every episode comes over with its own ID, so no app plays one twice.
b At your old host, find Redirect feed (sometimes Move to a new host), paste your new MilitaryVoices feed address and save.
c Back here, press Check the redirect. When it says forwarding works, you're done: Apple and Spotify move over as each checks in, usually within a few days. Keep your old host's account until they have.
Moving your show away
a Set up the show at your new host first.
b Here, open Show details and paste the new host's feed into Moving to another host?. Your feed then sends every app a 301 to the new address, and tells Apple the new one too.
c Leave it in place for at least four weeks before deleting the show here, so every app has time to follow.
7 Help and contact
Email us: hello@militaryvoices.ai. A person reads every message and writes back.
Search the help, or ask Alex: militaryvoices.ai/help.
Your feed, your episodes and your downloads are on your Podcast screen.
Open my Podcast screen

=== MILITARYVOICES.AI PLATFORM · www.militaryvoices.ai/help/youtube ===
All help Help · Going out live
Your slot on your own YouTube, too
Your slot airs on The Podcast Marathon either way. Connect your channel once and it goes out there as well — live, to your audience, at the same time. No stream key to find. Five minutes, start to finish.
Your browser can't play this video. The steps below cover the same ground.
45 seconds: the whole connection, start to finish.
1 Connect your channel
Sign in to your dashboard, open Integrations, and press Connect YouTube. Use the Google account that owns your channel.
Open Integrations
2 Get past Google's warning
Google shows "Google hasn't verified this app". That's us — our verification with Google is in review and hasn't come back yet. The permission only lets us open a live broadcast on your channel at your booked time; we can't post, edit or read anything else. Three presses get you through it.
a Press Advanced.
b Press Go to Military Voice (unsafe). It isn't — that word is Google's default wording until the review is done.
c Press Continue.
3 Choose what goes to your channel
Straight after connecting, the card asks one question: just my segment, or the entire show.
Just my segment — when your slot comes up, the producer opens a broadcast on your channel and your audience watches you there. Nothing else appears on your channel.
The entire show — all sixteen hours, first show to last, on your channel too. A broadcast is scheduled on your channel for 7:00 AM Eastern on 5 October and starts when we do. YouTube keeps a recording of the first twelve hours of a live stream, so the replay on your channel ends around 7 PM even though the stream runs to 11.
You can change your answer any time from the same card.
4 Before the day
Live streaming has to be switched on for your channel. YouTube asks for a verified phone number and takes up to 24 hours the first time you enable it — do it this week, not on the day. In YouTube Studio: Create → Go live.
YouTube is the only place we can send to directly. Facebook, LinkedIn and X don't allow it without a third-party tool. Reply to any email from us and we'll set one up with you.
Something not working? Reply to any email from us, or ask Alex in the green room on the day.
Ready? It takes about five minutes.
Connect my YouTube

=== MILITARYVOICES.AI PLATFORM · www.militaryvoices.ai/help/zoom ===
All help Help · Your recordings
Your Zoom recordings, straight into your Library
Connect your Zoom account to MilitaryVoices.ai once. Your cloud recordings then come into your Library, ready for Pōstify to make clips and a clean episode. The app only reads your recordings. It never changes, deletes or shares anything in your Zoom account.
1 Adding the app
Before you start, you need:
A MilitaryVoices.ai podcaster account. Sign in at your dashboard with your email and the 6-digit code we send you.
A Zoom account with cloud recording switched on. Cloud recording comes with Zoom's paid plans. To check, sign in at zoom.us and open Settings → Recording. Cloud recording should be on.
Recordings saved to the cloud. In a meeting, press Record, then Record to the Cloud. Recordings saved to your computer stay on your computer, so the app can't see them.
Then connect it:
a Sign in to your dashboard and open Integrations.
b On the Zoom card, press Connect Zoom.
c Zoom opens. Sign in if it asks, check what the MilitaryVoices app can see, and press Allow.
d You're back on Integrations with "Zoom is connected". The card now says Connected as and your Zoom email address.
Pressed Decline by mistake? You'll see "Zoom wasn't connected". Nothing was saved, so press Connect Zoom again. If you see "That took too long", the approval waited more than 15 minutes. Press Connect Zoom again.
Open Integrations
2 Using it
New recordings come in on their own
When Zoom finishes processing a cloud recording, it tells us, and the video comes into your Library. Zoom can take a while after the meeting ends. It emails you when the recording is ready, and ours starts coming in then.
The switch on the Zoom card, Bring each new cloud recording into my Library on its own, turns this on and off. It's on when you first connect.
Bringing in past recordings
a On the Zoom card, press Import past recordings.
b You'll see your cloud recordings from the last 30 days, newest first, with the date, length and size.
c Press Import next to the one you want. It changes to In your Library.
No video next to a recording means it has no MP4 video to bring in, such as an audio-only recording.
What happens next
Each recording shows in your Library as its own episode. It says "Importing from Zoom…" for a few minutes while we copy it, then it's ready to play.
Open the ⋯ menu on it and choose Pōstify it to make clips and a clean episode. You can also download it or move it to a folder.
Zoom can save a meeting in several views. We keep one video: the shared screen with the speaker if there is one, otherwise the active speaker, otherwise any finished MP4.
The recording stays in your Zoom account too. We copy it; we never move or delete it.
Good to know
The list covers the last 30 days. For an older recording, download it from Zoom (zoom.us → Recordings) and upload it to your Library.
MP4 video only. Audio-only files, chat and transcripts aren't brought in.
Cloud recordings only. Upload recordings saved on your computer in the Library yourself.
Recordings from before you connected don't come in on their own. Use Import past recordings.
"Couldn't bring it in" on a Library card means the copy failed. Write to us and we'll look.
3 Removing the app
You can remove it either way. Both delete the connection straight away.
From MilitaryVoices.ai
a Sign in to your dashboard and open Integrations.
b On the Zoom card, press Disconnect. You'll see "Zoom disconnected". We ask Zoom to revoke our access and delete the connection.
From Zoom
a Sign in to the Zoom App Marketplace.
b Open Manage, then Added Apps.
c Find MilitaryVoices and press Remove. Zoom tells us, and we delete the connection.
What gets deleted, and what stays
Deleted at once: your Zoom access and refresh tokens, your Zoom user ID, account ID and email address, and your automatic-import setting. New recordings stop coming in.
Stays until you delete it: videos you already imported. They're yours to keep. To delete one, open your Library, press ⋯ on it, then Delete. That removes our copy of the video, with its clean and edited copies and its clips.
A recording that was already coming in when you disconnected may still finish. Delete it from your Library if you don't want it.
Want everything gone? Write to hello@militaryvoices.ai and we'll delete your account and all of your data.
Nothing in your Zoom account changes. Your recordings stay in Zoom.
4 What we access and store
The app asks Zoom for three permissions. In plain words:
See your Zoom profile.
user:read:user Read once, when you connect, for your Zoom user ID and email. That's how we match new recordings to you and show who's connected.
See the list of your cloud recordings.
cloud_recording:read:list_user_recordings Used for the Import past recordings list.
See the files in a recording.
cloud_recording:read:list_recording_files Used to find and download the MP4 of a recording you import, or of each new one while automatic import is on.
Zoom also sends us two notices: when a new cloud recording is ready, and when you remove the app.
What we store
Your Zoom access and refresh tokens, Zoom user ID, account ID and email. They're kept in our database, encrypted at rest, and never sent to your browser. They're deleted when you disconnect or remove the app.
The videos you import, in private storage (Cloudflare R2), with each meeting's topic, date, length and size so your Library can show them. They stay until you delete them.
What we never do
Change, delete or share anything in your Zoom account.
Read your meetings, chats, contacts or calendar.
Sell your data, or use it for advertising.
The full detail, and your rights over your data, are in our privacy policy.
5 Help and contact
Email us: hello@militaryvoices.ai. A person reads every message and writes back.
Search the help, or ask Alex: militaryvoices.ai/help.
The small print: privacy policy and terms of service.
Ready? It takes about a minute.
Connect my Zoom

=== MILITARYVOICES.AI PLATFORM · www.militaryvoices.ai/help/smartlink ===
All help Help · SmartLink
Your SmartLink: the top of your page and your talking intro
Your SmartLink is your page at militaryvoices.ai/you: your podcast, your links, and a way for listeners to reach you. It's free. Press SmartLink in the menu to edit it; the phone beside the editor shows your changes as you make them.
1 The Hero top
Hero puts your photo right across the top of your page, with your name over it.
a Open the Design tab. Under Layout, in Top of the page, pick Hero.
b With a photo on your page, four sliders appear under it:
Name size: smaller or bigger.
Name position: moves your name, and what's under it, up or down the photo.
Photo position: moves the photo up or down, if it cuts off a head.
Photo size: zooms in. The photo always fills the top.
c Not happy? Press Reset to put them all back.
Your photo or logo already says your name? Turn off Show my name.
2 Your talking intro
Your profile photo, saying hello to everyone who opens your page. It sits in a bubble; visitors tap it to hear you. Up to 45 seconds.
a Open the Profile tab and add a clear profile photo of your face, looking at the camera.
b Find Your talking intro. Choose In my voice and press Record my hello, or Type it, pick a voice.
c Press Make my talking intro. It takes a few minutes; keep working, even on another tab.
d When it's ready, it's on your page. Use the switch to turn it off or on, tap a spot on the little phone under Where it goes to move it, and pick What the bubble says.
Want a different one? Press Make a new one.
3 Picking a voice
With Type it, pick a voice, type what you'd like to say, choose Man's voice or Woman's voice, then pick one from the list. Press Hear it for a sample first.
Marine voices
Three voices were picked for this community:
Brock: loud Marine sergeant.
Sarge: rough, war-torn sergeant.
Jerry: gruff, gritty commander.
They're under Man's voice, with the others.
4 Email your fans
Everyone who signs up with the Stay in touch block on your SmartLink is on your list, and you can write to them.
a In the menu, under Audience, press Email your fans. It shows how many fans have signed up.
b Press New email. Start from a personal note, an announcement or a newsletter, or press Or have SI write it and say what it's about.
c Add blocks (text, heading, picture, button, callout, divider) and watch the email on the right, on a phone or a computer. Press Send me a test to see it in your own inbox.
d Press Review & send, then Send now or Schedule.
It comes from Your show via MilitaryVoices.ai, and replies come to you. Your SmartLink's cover picture sits at the top. You can send one email a day, and every fan can unsubscribe from your emails in one click. People who only asked for a reminder of your show aren't on this list.
5 Help and contact
Email us: hello@militaryvoices.ai. A person reads every message and writes back.
Search the help, or ask Alex: militaryvoices.ai/help.
Edit your page and see it change on the phone beside it.
Open my SmartLink

=== MILITARYVOICES.AI PLATFORM · www.militaryvoices.ai/help/guests ===
All help Help · Guests
Book a guest, or be one
Two tabs on your show find people to have on, and shows to go on. They search Discovery for you. Discovery is free, and it's added for you with your first search.
1 Book a guest
a Press Podcast in the menu, open your show, and choose the Book a guest tab.
b Search by a topic they're known for, or a name. People who've been guests on podcasts come up, the most-booked first.
c Open someone. Under Book them:
Invite to my show puts them on your Marathon slot's guest list. They get their own link into your green room: nothing to sign up for.
Find their email (below).
Save to Guests keeps them for later.
2 Find their email
Find their email looks a person up by their X account. Each one uses a contact email from your month:
10 a month free, or 100 with Discovery Pro.
Used them all? Each one after that is 1 credit. Once you've paid for one, it's free to see again.
No X account on file for them? The button is greyed out.
See credits and Discovery Pro.
3 Be a guest
a On your show, choose the Be a guest tab.
b Search what you'd talk about: leadership, transition, faith. You'll see podcasts that have guests and put out an episode in the last 90 days.
c Open one to see its host and how to reach them.
d Under Pitch yourself, say what you'd talk about (or leave it and we'll suggest), then press Write my pitch. SI writes it from your SmartLink and your show.
e Read it and change anything. Press Open in my email to send it from your own email, or Copy. Write another gives you a fresh one.
No email for a show? Paste your pitch into their website's contact form, or send it to them on social.
4 Search and Saved
At the top of both tabs, switch between Search and what you've saved: Saved guests on Book a guest, Saved shows on Be a guest.
Open one to pick up where you left off.
Press its ✕ to take it off the list.
Your saved guests are in Discovery too, under Saved.
5 Help and contact
Email us: hello@militaryvoices.ai. A person reads every message and writes back.
Search the help, or ask Alex: militaryvoices.ai/help.
Book a guest and Be a guest are tabs on your show.
Open my Podcast screen

=== MILITARYVOICES.AI PLATFORM · www.militaryvoices.ai/help/account ===
All help Help · Your account
Your plan, credits, and what you deleted
Two things live in your account menu (press your photo, top right): Plan & billing and Recently deleted.
1 What's free
Your SmartLink, podcast hosting and Ask my show are free, always. So is Discovery, with 10 contact emails a month. Your first Pōstify episode is free too.
2 Pōstify plans
A plan gives you credits every month for clips and clean episodes.
Creator, $19.95 a month: 30 credits a month, 4 clips an episode.
Pro, $49 a month: 90 credits a month, 6 clips an episode.
Both take the MilitaryVoices.ai bar off your SmartLink.
a Open the account menu and press Plan & billing.
b Press Upgrade to Creator or Upgrade to Pro. Checkout is secure, by Stripe.
Paying yearly gets two months free: choose Yearly in Pōstify's Pick a plan window. Cancel any time.
3 Credits
Credits pay for clips, clean episodes, and contact emails past your monthly ones. Credits you buy don't run out.
An episode in Pōstify: 8 credits (12 on Pro) for every clip in all three shapes with animated captions, and the clean episode. Classic captions: 5 (7 on Pro).
Music and text edits are included.
A contact email in Discovery, past your monthly ones: 1 credit. Once paid for, it's free to see again.
To top up, press Buy 50 credits · $35 in Plan & billing. On a monthly plan, if you run out, extra credits go on your next bill, up to a limit you set in Pōstify.
4 Discovery Pro
Discovery is free with 10 contact emails and 200 profile look-ups a month. Discovery Pro raises that to 100 contact emails and 1,000 look-ups a month, for $29 a month. You don't need a Pōstify plan for it.
a In Plan & billing, press Add Discovery Pro.
b Once it's on, the same card shows how many contact emails you have left this month, and Manage.
Past your monthly contact emails, each one is 1 credit. See Book a guest, or be one.
5 Manage billing
On a plan, Plan & billing shows your plan, your credits a month and when it renews. Press Manage billing to open Stripe's secure billing page: change your card, see your invoices, or cancel.
If a payment didn't go through, your plan says so. Update your card in Manage billing.
6 Recently deleted
Anything you delete waits here for 15 days, so you can put it back just as it was. After that it's gone for good.
Library episodes, with their clean and edited copies and their clips.
Clips. They go back with their episode.
Podcast episodes. A published one returns to your feed as the same episode.
Whole podcasts, with their episodes. The feed comes back on.
Files you've uploaded.
a Open the account menu and press Recently deleted. Each item shows how many days it has left.
b Press Put it back. It's back where it was.
Want it gone now? Press Delete now. That can't be undone.
Deleting a podcast episode takes it out of your feed, and the apps drop it on their next check. It doesn't take it off YouTube: if you posted it there, remove it in YouTube Studio.
7 Help and contact
Email us: hello@militaryvoices.ai. A person reads every message and writes back.
Search the help, or ask Alex: militaryvoices.ai/help.
Your plan, credits and Discovery Pro are in one place.
Open Plan & billing

=== THE PODCAST MARATHON (yearly event) · www.militaryvoices.ai/faq ===
MilitaryVoices.ai — The platform for military voices
All help Help · FAQ
Questions, answered.
Everything podcasters and listeners ask about The Podcast Marathon. Search, or jump to your section.
General For podcasters For listeners
General
What is the Podcast Marathon?
26.2 miles of live and ‘Best of MilVet’ podcasting for National Military Podcast Day—featuring back-to-back shows, special guests, and stories from the military and veteran community, streaming around the clock. Shows hand off to each other every 30 minutes, so someone is always on the air.
When is it?
It starts Mon, Oct 5 at 7:00 AM US Eastern and runs for 16 hours. Every time on this site is shown in your own time zone, and you can switch zones on the schedule and agenda.
Who is hosting?
Riccoh Player. Thirty-three years in the Marine Corps, five combat tours, an Emmy, and a seat beside a global media executive. He anchors the day and hands off to each show as it goes live.
Does it cost anything?
No. It's free for podcasters to claim a slot and free for listeners to follow along.
For podcasters
Who can claim a slot?
Veteran and military-community podcasters. If your show is by, for, or about the military community, you belong on the board. Solo hosts and two-person shows are both welcome.
How do I claim a slot?
Three steps. Pick an open time on the schedule, enter your email and the one-time code we send you, then set up your show once with a photo, your show name, and your RSS feed. Your slot is confirmed the moment you save.
Do I need a password?
No. Every sign-in uses a 6-digit code emailed to you. Your email is your account, so use the same one each time you come back.
How long is a slot, and how much of it am I on the air?
Each slot is 30 minutes. You're live for 25 of them, with a 5-minute handoff after your show for the transition to the next podcaster. Your confirmation email and your card on the agenda both show the exact on-air window.
Can I hold more than one slot?
One slot per show. If you want a different time, open your dashboard, use the pencil on your slot card to release it, and pick another. Choosing a new time from the schedule while you hold one swaps it for you.
Can I change or cancel my slot?
Yes, any time before the event from your dashboard. Releasing a slot puts it straight back on the open schedule for someone else.
Can I play an episode I already recorded instead of going live?
Yes. In your profile, under "How your slot runs", choose Play a recorded episode and paste a link to the file — an unlisted YouTube or Vimeo link, or Google Drive, Dropbox, or WeTransfer all work. Set sharing so anyone with the link can view it. We download it and check the audio before the event. You then pick whether to open with a short live virtual intro on camera, or go straight into the recording with nothing needed from you on the day.
Where do I broadcast from?
Your own setup. Record or stream from wherever you normally do. We give you the time block, the lineup, and the audience. Show-day connection details are emailed to every confirmed podcaster before the event. If you're playing a pre-recorded episode instead, you don't need to be anywhere unless you chose the live virtual intro.
Why do you ask for my RSS feed?
It's how we pull your episodes so listeners can hit play right from your card on the lineup, and follow your show after your slot. It's optional but strongly recommended. You'll find it in your hosting platform's settings (Buzzsprout, Spotify for Creators, Libsyn, Transistor, Podbean, and the rest all have one).
What does connecting my social accounts do?
Your connected accounts show on your card with your avatar and follower count, so listeners can tap straight through and follow you. We only read the public profile info. Nothing is ever posted on your behalf.
What should I have ready?
Start with the podcaster guide, which walks through show day end to end. In short: a good square photo of yourself, your show name, and your RSS feed. If you're bringing a video intro or outro, slides, or images, tick those boxes in your profile so the production team can plan the transitions. If you'd like to be paired with an interviewer, say so there too and we'll line someone up before air time.
For listeners
Do listeners need to claim anything?
No. Claiming is only for podcasters. As a listener, head to the agenda to see who's on and when, then pick the shows you want to catch.
How do I know when a show I care about is starting?
Every show's card on the agenda has a Remind me button. Give us your name and email (and a mobile number if you'd like a text) and we'll message you before that show goes live. The confirmation email includes add-to-calendar links for Google, Outlook, and Apple.
Where do I watch or listen?
On the day, the agenda is your home base. Each show's card links to the podcaster's channels, and stream details are posted there before the event starts.
I'm overseas. Will the times make sense?
Yes. The schedule and agenda both show times in the zone you pick, and default to wherever your device is. Twenty-four hours means there's something live no matter where you are.
Can I share a show?
Every card has a Share button that copies a ready-to-post line with the show, the host, and the time.
Still have a question?
Ask Alex, or email hello@militaryvoices.ai and a human will get back to you.

=== THE PODCAST MARATHON (yearly event) · www.militaryvoices.ai/prepare ===
MilitaryVoices.ai — The platform for military voices
Podcaster guide
Getting ready for your slot
Everything you need to have in hand before you go on the air, and what happens on the day.
Why we're doing this
National Military Podcast Day
This is a celebration of the voices and stories of the military community: those serving now, those who served, and the families, organizations and supporters who stand behind them. For 16 hours we hand the microphone from one show to the next so those stories run without a break, in every time zone, all day and all night.
Your slot is a piece of that. The better prepared you are, the more your story lands.
Your time
Enter the studio 10 minutes before your on-air time. That gives us a moment to check your camera and sound, load anything you've sent us, and hand off cleanly from the show before you.
What to send us beforehand
Get your material to us early
Anything you want played, shown or read out needs to reach us before show day so it's loaded and tested. Upload it in the Show materials panel on your dashboard and it attaches to your slot automatically. Files up to 50MB upload directly; anything larger, paste a link.
Any video or images you want on screen
Intro, outro, mid-roll, lower thirds, photos, slides — anything you'd like us to play or show during your segment.
Name each file for what it is: "intro", "outro", "mid-roll", "photo-1". Clear names are what let us cue the right thing at the right moment.
Who's appearing with you
Full names and titles for every guest and co-host, exactly as you want them read on air and shown on screen.
If you're being interviewed, your questions
Send the questions you'd like to be asked and a short note on the topic. It keeps the conversation on the ground you want to cover.
Anything we can help promote
Your podcast's goals or mission, a launch, a campaign, a cause. Tell us what matters and we'll work it into how we introduce and share your slot.
Label everything. A file called "intro" gets played as your intro. A file called "final_v3_REAL.mp4" gets a phone call from us on show day.
The studio
Where you'll actually be
You join from wherever you record. We'll email you the studio link and how to sign in ahead of the event, so all you need on the day is that link, your microphone and your camera.
A look inside the studio is coming shortly.
We'll add a walkthrough here before the event so nothing on the day is a surprise.
One thing to check now
Make sure your profile says how you normally record or stream, and what platform you use. It tells the studio team what to expect from you before you ever join.
Still have questions?
The FAQ covers slot lengths, changing your time, pre-recorded episodes and more. Anything it doesn't answer, just reply to any email from us.
`;
