// Alex's knowledge base, from the help articles exactly as visitors read them.
// Loads each page in headless Chrome (they render in the browser), keeps the
// article text and writes server/helpArticles.ts. Re-run after changing any
// help article, FAQ or the podcaster guide, then commit:
//   node scripts/build-help-kb.mjs [origin]
import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";

const ORIGIN = (process.argv[2] || "https://www.militaryvoices.ai").replace(/\/+$/, "");
const CHROME = process.env.CHROME || "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome";
const PAGES = [
  ["/help/rooms", "platform"], ["/help/library", "platform"], ["/help/postify", "platform"], ["/help/podcast", "platform"],
  ["/help/youtube", "platform"], ["/help/zoom", "platform"], ["/help/zoom-story", "platform"], ["/help/smartlink", "platform"], ["/help/guests", "platform"],
  ["/help/account", "platform"], ["/faq?all", "marathon"], ["/prepare", "marathon"],
];

const text = (html) => {
  const main = html.match(/<main[\s\S]*?<\/main>/i)?.[0] ?? html;
  return main
    .replace(/<(script|style|svg|nav|header|footer|button)[\s\S]*?<\/\1>/gi, " ")
    .replace(/<\/(p|h[1-6]|li|div|section|tr|summary|details)>/gi, "\n").replace(/<br\s*\/?>/gi, "\n")
    .replace(/<[^>]+>/g, " ")
    .replace(/&amp;/g, "&").replace(/&#x27;|&#39;/g, "'").replace(/&quot;/g, '"').replace(/&nbsp;/g, " ").replace(/&lt;/g, "<").replace(/&gt;/g, ">")
    .replace(/[ \t]+/g, " ").replace(/ ([.,;:!?)])/g, "$1").replace(/\( /g, "(")
    .split("\n").map((l) => l.trim()).filter(Boolean).join("\n");
};

const out = [];
for (const [path, kind] of PAGES) {
  const html = execFileSync(CHROME, ["--headless=new", "--disable-gpu", "--virtual-time-budget=15000", "--dump-dom", ORIGIN + path], { encoding: "utf8", maxBuffer: 50e6, stdio: ["ignore", "pipe", "ignore"] });
  const t = text(html);
  if (t.length < 400) throw new Error(`${path} came back nearly empty (${t.length} chars)`);
  out.push(`=== ${kind === "marathon" ? "THE PODCAST MARATHON (yearly event)" : "MILITARYVOICES.AI PLATFORM"} · ${ORIGIN.replace(/^https?:\/\//, "")}${path.replace(/\?.*$/, "")} ===\n${t}`);
  console.log(path, t.length, "chars");
}
const body = out.join("\n\n").replace(/`/g, "'").replace(/\$\{/g, "$ {");
writeFileSync("server/helpArticles.ts", `// Generated by scripts/build-help-kb.mjs from the live help articles, FAQ and podcaster guide.\n// Don't edit by hand: change the article, deploy, and re-run the script.\nexport const HELP_ARTICLES = \`\n${body}\n\`;\n`);
console.log("wrote server/helpArticles.ts", body.length, "chars");
